
name: Umi-ui
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build_umi_ui:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-node@v2.1.4
      - run: |
          npm install --ignore-scripts
          npm run lint-ui


